version: '3.8'

services:
  app:
    container_name: avito_fastapi_app
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${API_OUTSIDE_PORT}:${API_INSIDE_PORT}
    environment:
      - DATABASE_URL = "postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}"
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: avito_postgresql_db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: